### ISSUE TITLE
How do I configure this globally? 

### ISSUE THREAD

**Issue by timchan-lumoslabs** [rtfpessoa/coursier-s3#3]
https://github.com/alexarchambault/coursier has instructions on adding coursier to `~/.sbt/0.13/plugins/build.sbt` to enable it globally. 

How do I do the same for coursier-s3?

**Comment by rtfpessoa** [comment]
It should be very similar. But I never tried something like that.

If you add
```
resolvers += Resolver.bintrayRepo("rtfpessoa", "maven")
libraryDependencies += "rtfpessoa" %% "coursier-s3" % "1.0.0-alpha.1"
```
to `~/.sbt/0.13/plugins/build.sbt` you should get the plugin there but now you still need to enable the s3c url handler.

This part I am not sure. 

But mainly you just need to invoke:

```
import coursier.cache.protocol.S3cHandler
S3cHandler.setupS3Handler()
```

Somewhere in your sbts.

I just saw that @alexarchambault did some changes in his account and I am asking if he was able to pass this part.

**Comment by rtfpessoa** [comment]
Check https://github.com/coursier/coursier/issues/164#issuecomment-292600251 for some new developments.
