### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by timchan-lumoslabs** [rtfpessoa/coursier-s3#4]
Am I supposed to remove the following plugin that I'm currently using: 
`addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.9.0")`

I'm getting this error:

`Cannot instantiate coursier.cache.protocol.S3cHandler: java.lang.ClassCastException: coursier.cache.protocol.S3cHandler cannot be cast to java.net.URLStreamHandlerFactory (coursier.cache.protocol.S3cHandler cannot be cast to java.net.URLStreamHandlerFactory)
`

**Comment by rtfpessoa** [comment]
You are missing the:

```
import coursier.cache.protocol.S3cHandler
S3cHandler.setupS3Handler()
```

**Comment by ChetanBhasin** [comment]
I tried the above, but it gives the following error:

```
build.sbt:4: error: type mismatch;
 found   : Unit
 required: sbt.internals.DslEntry
S3cHandler.setupS3Handler()
                         ^
```

**Comment by rtfpessoa** [comment]
After the initial problems I did not got much time to fix this and stopped developing this plugin.

Check https://github.com/coursier/coursier/issues/164#issuecomment-292600251 for some new developments.
